
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mlflow","app.kubernetes.io/instance":"mlflow"},"name":"ml
flow-service","namespace":"mlflow"},"spec":{"ports":[{"name":"http","port":5000,"targetPort":5000}],"selector":{"app":"mlflow"},"type":"ClusterIP
"}}
  labels:
    app: mlflow
    app.kubernetes.io/instance: mlflow
  name: mlflow-service
  namespace: mlflow
spec:
  - 172.20.172.203
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


