apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-redis-exporter
  endpoints:
    - port: redis-exporter
      interval: 30s
