apiVersion: v1
kind: Service
metadata:
  name: llm-platform-api
  labels:
    app: llm-platform-api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: llm-platform-api
