apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: kubeflow
spec:
  type: ExternalName
  externalName: mlflow.mlflow.svc.cluster.local
  ports:
    - port: 5000
      targetPort: 80
