apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels: {app: ml-pipeline-ui}
  template:
    metadata:
      labels: {app: ml-pipeline-ui}
    spec:
      containers:
        - name: ml-pipeline-ui
          image: gcr.io/ml-pipeline/frontend:2.2.0
          imagePullPolicy: IfNotPresent
          env:
            - {name: ML_PIPELINE_SERVICE_HOST, value: ml-pipeline}
            - {name: ML_PIPELINE_SERVICE_PORT, value: "8888"}
          ports:
            - containerPort: 3000
